apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-a
spec:
  template:
    spec:
      containers:
      - name: sleep
        env:
         - name: FOO_ENV
           value: foo
         - name: BAR_ENV
           value: bar
         - name: HOGE_ENV
           value: hoge2
         - name: TEST_A
           value: test_a
         - name: TEST_B
           value: test_b
