apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-a
spec:
  template:
    spec:
      containers:
      - name: sleep
        env:
         - name: FOO_ENV
           value: foo
         - name: BAR_ENV
           value: bar
         - name: HOGE_ENV
           value: hoge2
         - name: AAA_ENV
           value: aaa
         - name: BBB_ENV
           value: bbb

