apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-a
spec:
  template:
    spec:
      containers:
      - name: sleep
        env:
         - name: XXX_ENV
           value: xxx
         - name: YYY_ENV
           value: yyy
         - name: BAR_ENV
           value: bar
         - name: HOGE_ENV
           value: hoge2
         - name: AAA_ENV
           value: aaa
         - name: BBB_ENV
           value: bbb
         - name: CCC_ENV
           value: ccc
         - name: DDD_ENV
           value: bbb
         - name: TEST_A
           value: test_a
         - name: TEST_B
           value: test_b
         - name: TEST_C
           value: test_a
         - name: TEST_D
           value: test_c
         - name: TEST_D
           value: test_d
