apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-b
spec:
  template:
    spec:
      containers:
      - name: sleep
        env:
         - name: FOO_ENV
           value: foo
         - name: BAR_ENV
           value: bar
         - name: HOGE_ENV
           value: hoge1
         - name: PARAM_A
           value: param_a
         - name: PARAM_B
           value: param_b
         - name: PARAM_C
           value: param_c
